name: "CI"

on:
  pull_request:
    paths:
      - "**.php"
      - "**.css"
      - "**.js"
      - "phpcs.xml"
      - "csscs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Install PHP_CodeSniffer
        run: php phpcs.phar --version

      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "*.php,*.css,*.js" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
          scope: files